/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class traildb_TrailDB */

#ifndef _Included_traildb_TrailDB
#define _Included_traildb_TrailDB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     traildb_TrailDB
 * Method:    openDb
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_traildb_TrailDB_openDb
  (JNIEnv *, jobject, jstring);

/*
 * Class:     traildb_TrailDB
 * Method:    getMeta
 * Signature: (J)Ltraildb/TrailDBMeta;
 */
JNIEXPORT jobject JNICALL Java_traildb_TrailDB_getMeta
  (JNIEnv *, jobject, jlong);

/*
 * Class:     traildb_TrailDB
 * Method:    getUUID
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_traildb_TrailDB_getUUID
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
