/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class traildb_constructor_TrailDBNativeConstructor */

#ifndef _Included_traildb_constructor_TrailDBNativeConstructor
#define _Included_traildb_constructor_TrailDBNativeConstructor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     traildb_constructor_TrailDBNativeConstructor
 * Method:    open
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_traildb_constructor_TrailDBNativeConstructor_open
  (JNIEnv *, jobject, jstring, jobjectArray);

/*
 * Class:     traildb_constructor_TrailDBNativeConstructor
 * Method:    add
 * Signature: (J[BJ[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_traildb_constructor_TrailDBNativeConstructor_add
  (JNIEnv *, jobject, jlong, jbyteArray, jlong, jobjectArray);

/*
 * Class:     traildb_constructor_TrailDBNativeConstructor
 * Method:    close
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_traildb_constructor_TrailDBNativeConstructor_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
