/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class traildb_TrailDBCursor */

#ifndef _Included_traildb_TrailDBCursor
#define _Included_traildb_TrailDBCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     traildb_TrailDBCursor
 * Method:    peek
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_traildb_TrailDBCursor_peek
  (JNIEnv *, jobject, jlong);

/*
 * Class:     traildb_TrailDBCursor
 * Method:    constructor
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_traildb_TrailDBCursor_constructor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     traildb_TrailDBCursor
 * Method:    getUUID
 * Signature: (JJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_traildb_TrailDBCursor_getUUID
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
